---
title: "Multiple glm regression"
format: html
editor: visual
---

## Multiple Regression (not logistic)

So far, we've looked at linear regression, a method we use when we are interested in examining the relationship between a continuous response and continuous predictor variable.

Sometimes, we have more than one predictor variable we are interested in, and we can examine the relationship between more than one predictor variable and the response variable. This is called "multiple regression."

Multiple linear regression makes the same assumptions about our predictor variables as simple bivarite linear regression, which are that:

-   The data have a linear (vs. non-linear) relationship.

-   The data are normally distributed

-   The residual values (remember, these are the measures of the distance between the actual points and the predicted regression line) have constant variance for each level of the predictor variable.

We have been using autoplot to check that we are meeting these assumptions.
